const fs = require('fs');
const path = require('path');
require('dotenv').config();

const configTemplate = `// ═══════════════════════════════════════════════════════════
//  firebase-config.js — Firebase Web SDK (Compat) Config
//  This file is automatically generated from .env
// ═══════════════════════════════════════════════════════════

const FIREBASE_CONFIG = {
  apiKey:            "${process.env.FIREBASE_API_KEY}",
  authDomain:        "${process.env.FIREBASE_AUTH_DOMAIN}",
  projectId:         "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket:     "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId:             "${process.env.FIREBASE_APP_ID}"
};

export default FIREBASE_CONFIG;
`;

const configPath = path.join(__dirname, 'firebase-config.js');
fs.writeFileSync(configPath, configTemplate);

console.log('✅ firebase-config.js has been generated from .env');
